#!/bin/bash

read stats

function boolean() {
  case $1 in
    1) echo true ;;
    0) echo false ;;
    *) echo "Err: Unknown boolean value \"$1\"" 1>&2; exit 1 ;;
   esac
}

function push_to_database() {
  app_route=$1
  app_start_time_in_sec=$2
  app_stop_time_in_sec=$3
  app_start_status=$4
  app_stop_status=$5

  echo $CF_SLI_USERNAME
  if [ -n "$CF_SLI_USERNAME" ]
  then
    additional_params="-U $CF_SLI_USERNAME"
  fi

  echo "Inserting data into cf_sli using user $CF_SLI_USERNAME"

  psql $additional_params -c "insert into cf_sli values('$app_route', $app_start_time_in_sec,\
    $app_stop_time_in_sec, $(boolean $app_start_status), $(boolean $app_stop_status));"
}

app_route=$(echo $stats | jq '.app_route')
app_start_time_in_sec=$(echo $stats | jq '.app_start_time_in_sec')
app_stop_time_in_sec=$(echo $stats | jq '.app_stop_time_in_sec')
app_start_status=$(echo $stats | jq '.app_start_status')
app_stop_status=$(echo $stats | jq '.app_stop_status')

push_to_database $app_route $app_start_time_in_sec $app_stop_time_in_sec $app_start_status $app_stop_status
