#!/bin/bash

set -eux

: ${PGPASSWORD:?}
: ${PGUSER:?}
: ${PGHOST:?}
: ${PGPORT:?}

output=$0
stats=$(echo -e "$output" | tail -n 1)

psql \
  -U"${PGUSER}" \
  --host="${PGHOST}" \
  --port="${PGPORT}" \
  -c "CREATE TABLE IF NOT EXISTS cf_sli (
    route text,
    start_time float,
    stop_time float,
    start_status int,
    stop_status int,
    entry_time timestamp with time zone
  );"

app_route=$(echo $stats | jq '.app_route')
app_start_time_in_sec=$(echo $stats | jq '.app_start_time_in_sec')
app_stop_time_in_sec=$(echo $stats | jq '.app_stop_time_in_sec')
app_start_status=$(echo $stats | jq '.app_start_status')
app_stop_status=$(echo $stats | jq '.app_stop_status')


psql \
  -U"${PGUSER}" \
  --host="${PGHOST}" \
  --port="${PGPORT}" \
  -c "INSERT INTO cf_sli VALUES(
    ${app_route},
    ${app_start_time_in_sec},
    ${app_stop_time_in_sec},
    ${app_start_status},
    ${app_stop_status},
    now());"
